export { default as BranchDashboard } from './dashboard'
export { default as CashierPage } from './cashier'
export { default as ManageAppointmentPage } from './manage-appointment'
export { default as ManageBranchOrderPage } from './manage-branch-order'
export { default as ManageBranchWarrantyPage } from './manage-warranty'
export { default as BranchOrderDetailPage } from './manage-branch-order/branch-order-detail-page'
